# Generated by Django 3.0.3 on 2020-03-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_topic',
            field=models.CharField(default='Misc', max_length=300),
        ),
    ]
