# Generated by Django 3.0.3 on 2020-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_question_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
