# Generated by Django 3.0.3 on 2020-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0003_remove_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_comments',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
