# Generated by Django 3.0.3 on 2020-03-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0005_auto_20200329_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responders',
            field=models.ManyToManyField(related_name='responder', to='BaseApp.UserProfile'),
        ),
    ]
